### PR TITLE
chore: fix test reloading

### LINKED ISSUE #439: chore: fix test reloading
test reloading relies on `lein auto` right now, would be good to have it just run with a namespace reload instead

### PR DESCRIPTION
**Pull request by nmathew98**
changes:
- add [kaocha](https://github.com/lambdaisland/kaocha) test runner
- configure kaocha

notes:
- should be a straightforward swap, kaocha can do everything that we did before, output is also much less noisier than before
   - image
  - image

closes: #439

### CODE REVIEW

File: api/imigresen-api/src/imigresen_api/test/core.clj [hunk 1]
```diff
@@ -0,0 +1,39 @@
+(ns imigresen-api.test.core
+  (:require [clj-commons-exec :as exec])
+  (:gen-class))
+
+(def arguments (atom []))
+
+(defn test! [& args]
+  (let [command (into [] cat [["lein" "test"] args])]
+    (println "Running test command:" command)
+    (exec/sh command {:out System/out :err System/err})))
```
Comment (nmathew98) [inline api/imigresen-api/src/imigresen_api/test/core.clj]: this way is the same as `lein auto test`, we need a custom runner to only run test files for areas which have changed

still reloads everything here

Comment (nmathew98) [reply api/imigresen-api/src/imigresen_api/test/core.clj]: think `lein auto test` works fine for now, no need for the complexity
